# Generated by Django 4.1.5 on 2023-01-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
