# Generated by Django 4.1.5 on 2023-01-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_jacket',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
