# Generated by Django 4.1.5 on 2023-01-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApp', '0006_album_audio_file_alter_album_album_jacket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_jacket',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
